"""Tests for the ancestry-risk-profiler skill."""
import json
import math
import sys
from pathlib import Path

import pytest

SKILL_DIR = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(SKILL_DIR))

import ancestry_risk_profiler as arp
from clawbio.common.parsers import parse_genetic_file, genotypes_to_simple

DATA_DIR = SKILL_DIR / "data"
DEMO_FILE = DATA_DIR / "demo_patient_south_asian.txt"


# ---------------------------------------------------------------------------
# TestGenotypeParser — integration tests for clawbio.common.parsers usage
# (unit tests for parsing behaviour live in the common module's own test suite)
# ---------------------------------------------------------------------------


class TestGenotypeParser:
    def test_parse_demo_file_returns_nonempty_dict(self):
        result = genotypes_to_simple(parse_genetic_file(DEMO_FILE))
        assert isinstance(result, dict)
        assert len(result) > 10

    def test_parse_demo_file_skips_no_calls(self):
        result = genotypes_to_simple(parse_genetic_file(DEMO_FILE))
        for genotype in result.values():
            assert genotype != "" and "--" not in genotype

    def test_parse_demo_file_tcf7l2_present(self):
        result = genotypes_to_simple(parse_genetic_file(DEMO_FILE))
        assert "rs7903146" in result


# ---------------------------------------------------------------------------
# TestAncestryInference
# ---------------------------------------------------------------------------


class TestAncestryInference:
    def setup_method(self):
        self.panel = arp.load_aisnp_panel(DATA_DIR / "aisnp_panel.csv")

    def test_load_aisnp_panel_returns_dict(self):
        assert isinstance(self.panel, dict)
        assert len(self.panel) > 20

    def test_panel_has_required_keys(self):
        first = next(iter(self.panel.values()))
        for pop in ("AFR", "AMR", "EAS", "EUR", "SAS"):
            assert pop in first

    def test_infer_ancestry_sas(self):
        genotypes = genotypes_to_simple(parse_genetic_file(DEMO_FILE))
        result = arp.infer_ancestry(genotypes, self.panel)
        assert result["inferred_ancestry"] == "SAS"
        assert result["confidence"] in ("high", "medium", "low")

    def test_infer_ancestry_returns_all_scores(self):
        genotypes = genotypes_to_simple(parse_genetic_file(DEMO_FILE))
        result = arp.infer_ancestry(genotypes, self.panel)
        for pop in ("AFR", "AMR", "EAS", "EUR", "SAS"):
            assert pop in result["scores"]

    def test_infer_ancestry_eur_override(self, tmp_path):
        f = tmp_path / "eur.txt"
        f.write_text(
            "# This data file generated by 23andMe\n"
            "rs1426654\t15\t48426484\tAA\n"
            "rs3827760\t2\t108879812\tCC\n"
        )
        genotypes = genotypes_to_simple(parse_genetic_file(f, fmt="23andme"))
        result = arp.infer_ancestry(genotypes, self.panel, ancestry_override="EUR")
        assert result["inferred_ancestry"] == "EUR"
        assert result["overridden"] is True

    def test_ancestry_override_flag(self):
        genotypes = genotypes_to_simple(parse_genetic_file(DEMO_FILE))
        result = arp.infer_ancestry(genotypes, self.panel, ancestry_override="EAS")
        assert result["inferred_ancestry"] == "EAS"
        assert result["overridden"] is True

    def test_infer_ancestry_raises_on_zero_coverage(self):
        """Empty genotype dict must raise InsufficientCoverageError, not silently return EUR."""
        with pytest.raises(arp.InsufficientCoverageError):
            arp.infer_ancestry({}, self.panel)

    def test_infer_ancestry_raises_below_min_coverage(self):
        """A dict with fewer than MIN_AISNP_COVERAGE panel hits must raise."""
        panel_rsids = list(self.panel.keys())
        sparse_genotypes = {rsid: "AG" for rsid in panel_rsids[:5]}
        with pytest.raises(arp.InsufficientCoverageError) as exc_info:
            arp.infer_ancestry(sparse_genotypes, self.panel)
        assert "5" in str(exc_info.value)
        assert "--ancestry" in str(exc_info.value)

    def test_infer_ancestry_low_confidence_still_runs_with_enough_coverage(self):
        """With >= MIN_AISNP_COVERAGE hits but ambiguous signal, return result with confidence=low."""
        panel_rsids = list(self.panel.keys())
        # Use enough SNPs to pass the coverage threshold but pick neutral heterozygotes
        # so population likelihoods are similar
        enough_genotypes = {rsid: "AG" for rsid in panel_rsids[:arp.MIN_AISNP_COVERAGE + 5]}
        result = arp.infer_ancestry(enough_genotypes, self.panel)
        assert result["inferred_ancestry"] in ("AFR", "AMR", "EAS", "EUR", "SAS")
        assert result["aisnp_coverage"] >= arp.MIN_AISNP_COVERAGE

    def test_override_bypasses_coverage_check(self, tmp_path):
        """--ancestry override must work even with zero AISNP coverage."""
        f = tmp_path / "sparse.txt"
        f.write_text("# 23andMe\nrs9999999\t1\t100\tAG\n")
        genotypes = genotypes_to_simple(parse_genetic_file(f, fmt="23andme"))
        result = arp.infer_ancestry(genotypes, self.panel, ancestry_override="SAS")
        assert result["inferred_ancestry"] == "SAS"
        assert result["overridden"] is True


# ---------------------------------------------------------------------------
# TestRiskScoring
# ---------------------------------------------------------------------------


class TestRiskScoring:
    def setup_method(self):
        self.associations = arp.load_associations(
            DATA_DIR / "ancestry_risk_associations.json"
        )

    def test_compute_disease_risks_returns_list(self):
        genotypes = genotypes_to_simple(parse_genetic_file(DEMO_FILE))
        risks = arp.compute_disease_risks(genotypes, "SAS", self.associations)
        assert isinstance(risks, list)
        assert len(risks) > 0

    def test_disease_risk_has_required_fields(self):
        genotypes = genotypes_to_simple(parse_genetic_file(DEMO_FILE))
        risks = arp.compute_disease_risks(genotypes, "SAS", self.associations)
        r = risks[0]
        for field in ("disease", "combined_or", "aes", "or_eur_combined",
                      "variants_found", "aes_category"):
            assert hasattr(r, field), f"Missing field: {field}"

    def test_disease_risk_has_no_absolute_risk_pct_fields(self):
        """Absolute lifetime risk % was removed — double-counting the baseline is unsound."""
        genotypes = genotypes_to_simple(parse_genetic_file(DEMO_FILE))
        risks = arp.compute_disease_risks(genotypes, "SAS", self.associations)
        r = risks[0]
        assert not hasattr(r, "user_lifetime_risk_pct"), "user_lifetime_risk_pct must be removed"
        assert not hasattr(r, "baseline_lifetime_risk_pct"), "baseline_lifetime_risk_pct must be removed"

    def test_disease_risk_has_or_eur_combined(self):
        genotypes = genotypes_to_simple(parse_genetic_file(DEMO_FILE))
        risks = arp.compute_disease_risks(genotypes, "SAS", self.associations)
        t2d = next(r for r in risks if r.disease == "Type 2 Diabetes")
        assert isinstance(t2d.or_eur_combined, float)
        assert t2d.or_eur_combined > 0

    def test_t2d_surfaces_for_sas(self):
        genotypes = genotypes_to_simple(parse_genetic_file(DEMO_FILE))
        risks = arp.compute_disease_risks(genotypes, "SAS", self.associations)
        diseases = [r.disease for r in risks]
        assert "Type 2 Diabetes" in diseases

    def test_aes_gt1_for_sas_t2d(self):
        genotypes = genotypes_to_simple(parse_genetic_file(DEMO_FILE))
        risks = arp.compute_disease_risks(genotypes, "SAS", self.associations)
        t2d = next(r for r in risks if r.disease == "Type 2 Diabetes")
        assert t2d.aes > 1.0, f"Expected AES > 1 for SAS T2D, got {t2d.aes}"

    def test_aes_near_1_for_eur_t2d(self):
        genotypes = genotypes_to_simple(parse_genetic_file(DEMO_FILE))
        risks_eur = arp.compute_disease_risks(genotypes, "EUR", self.associations)
        risks_sas = arp.compute_disease_risks(genotypes, "SAS", self.associations)
        t2d_eur = next((r for r in risks_eur if r.disease == "Type 2 Diabetes"), None)
        t2d_sas = next((r for r in risks_sas if r.disease == "Type 2 Diabetes"), None)
        if t2d_eur and t2d_sas:
            assert t2d_sas.aes >= t2d_eur.aes, "SAS AES should be >= EUR AES for T2D"

    def test_diseases_ranked_by_aes(self):
        genotypes = genotypes_to_simple(parse_genetic_file(DEMO_FILE))
        risks = arp.compute_disease_risks(genotypes, "SAS", self.associations)
        aes_values = [r.aes for r in risks]
        assert aes_values == sorted(aes_values, reverse=True)

    def test_aes_category_assigned(self):
        genotypes = genotypes_to_simple(parse_genetic_file(DEMO_FILE))
        risks = arp.compute_disease_risks(genotypes, "SAS", self.associations)
        valid_cats = {"elevated by ancestry", "neutral", "reduced by ancestry"}
        for r in risks:
            assert r.aes_category in valid_cats

    def test_variants_found_list_nonempty_for_t2d(self):
        genotypes = genotypes_to_simple(parse_genetic_file(DEMO_FILE))
        risks = arp.compute_disease_risks(genotypes, "SAS", self.associations)
        t2d = next(r for r in risks if r.disease == "Type 2 Diabetes")
        assert len(t2d.variants_found) > 0


# ---------------------------------------------------------------------------
# TestReportGeneration
# ---------------------------------------------------------------------------


class TestReportGeneration:
    def test_generate_report_creates_markdown(self, tmp_path):
        genotypes = genotypes_to_simple(parse_genetic_file(DEMO_FILE))
        panel = arp.load_aisnp_panel(DATA_DIR / "aisnp_panel.csv")
        associations = arp.load_associations(DATA_DIR / "ancestry_risk_associations.json")
        ancestry_result = arp.infer_ancestry(genotypes, panel)
        risks = arp.compute_disease_risks(genotypes, ancestry_result["inferred_ancestry"], associations)
        arp.generate_report(risks, ancestry_result, tmp_path)
        assert (tmp_path / "ancestry_risk_report.md").exists()

    def test_report_contains_disclaimer(self, tmp_path):
        genotypes = genotypes_to_simple(parse_genetic_file(DEMO_FILE))
        panel = arp.load_aisnp_panel(DATA_DIR / "aisnp_panel.csv")
        associations = arp.load_associations(DATA_DIR / "ancestry_risk_associations.json")
        ancestry_result = arp.infer_ancestry(genotypes, panel)
        risks = arp.compute_disease_risks(genotypes, ancestry_result["inferred_ancestry"], associations)
        arp.generate_report(risks, ancestry_result, tmp_path)
        text = (tmp_path / "ancestry_risk_report.md").read_text()
        assert "research" in text.lower() and "medical" in text.lower()

    def test_report_contains_ancestry(self, tmp_path):
        genotypes = genotypes_to_simple(parse_genetic_file(DEMO_FILE))
        panel = arp.load_aisnp_panel(DATA_DIR / "aisnp_panel.csv")
        associations = arp.load_associations(DATA_DIR / "ancestry_risk_associations.json")
        ancestry_result = arp.infer_ancestry(genotypes, panel)
        risks = arp.compute_disease_risks(genotypes, ancestry_result["inferred_ancestry"], associations)
        arp.generate_report(risks, ancestry_result, tmp_path)
        text = (tmp_path / "ancestry_risk_report.md").read_text()
        assert ancestry_result["inferred_ancestry"] in text

    def test_figures_dir_created(self, tmp_path):
        genotypes = genotypes_to_simple(parse_genetic_file(DEMO_FILE))
        panel = arp.load_aisnp_panel(DATA_DIR / "aisnp_panel.csv")
        associations = arp.load_associations(DATA_DIR / "ancestry_risk_associations.json")
        ancestry_result = arp.infer_ancestry(genotypes, panel)
        risks = arp.compute_disease_risks(genotypes, ancestry_result["inferred_ancestry"], associations)
        arp.generate_report(risks, ancestry_result, tmp_path)
        assert (tmp_path / "figures").is_dir()

    def test_result_json_written(self, tmp_path):
        genotypes = genotypes_to_simple(parse_genetic_file(DEMO_FILE))
        panel = arp.load_aisnp_panel(DATA_DIR / "aisnp_panel.csv")
        associations = arp.load_associations(DATA_DIR / "ancestry_risk_associations.json")
        ancestry_result = arp.infer_ancestry(genotypes, panel)
        risks = arp.compute_disease_risks(genotypes, ancestry_result["inferred_ancestry"], associations)
        arp.generate_report(risks, ancestry_result, tmp_path)
        assert (tmp_path / "ancestry_risk_result.json").exists()
        data = json.loads((tmp_path / "ancestry_risk_result.json").read_text())
        assert "inferred_ancestry" in data
        assert "risks" in data

    def test_report_directs_to_gwas_prs(self, tmp_path):
        """Report must signpost gwas-prs for validated absolute risk estimates."""
        genotypes = genotypes_to_simple(parse_genetic_file(DEMO_FILE))
        panel = arp.load_aisnp_panel(DATA_DIR / "aisnp_panel.csv")
        associations = arp.load_associations(DATA_DIR / "ancestry_risk_associations.json")
        ancestry_result = arp.infer_ancestry(genotypes, panel)
        risks = arp.compute_disease_risks(genotypes, ancestry_result["inferred_ancestry"], associations)
        arp.generate_report(risks, ancestry_result, tmp_path)
        text = (tmp_path / "ancestry_risk_report.md").read_text()
        assert "gwas-prs" in text

    def test_report_no_absolute_lifetime_risk_claim(self, tmp_path):
        """Report must not present absolute lifetime risk %% claims (double-counting removed)."""
        genotypes = genotypes_to_simple(parse_genetic_file(DEMO_FILE))
        panel = arp.load_aisnp_panel(DATA_DIR / "aisnp_panel.csv")
        associations = arp.load_associations(DATA_DIR / "ancestry_risk_associations.json")
        ancestry_result = arp.infer_ancestry(genotypes, panel)
        risks = arp.compute_disease_risks(genotypes, ancestry_result["inferred_ancestry"], associations)
        arp.generate_report(risks, ancestry_result, tmp_path)
        text = (tmp_path / "ancestry_risk_report.md").read_text()
        assert "lifetime risk" not in text.lower() or "not a lifetime risk" in text.lower() or "gwas-prs" in text

    def test_report_aes_marked_exploratory(self, tmp_path):
        """Report must explicitly label AES as exploratory."""
        genotypes = genotypes_to_simple(parse_genetic_file(DEMO_FILE))
        panel = arp.load_aisnp_panel(DATA_DIR / "aisnp_panel.csv")
        associations = arp.load_associations(DATA_DIR / "ancestry_risk_associations.json")
        ancestry_result = arp.infer_ancestry(genotypes, panel)
        risks = arp.compute_disease_risks(genotypes, ancestry_result["inferred_ancestry"], associations)
        arp.generate_report(risks, ancestry_result, tmp_path)
        text = (tmp_path / "ancestry_risk_report.md").read_text()
        assert "exploratory" in text.lower()

    def test_report_distinguishes_genetic_ancestry_from_ethnicity(self, tmp_path):
        """Report must explicitly clarify that inferred ancestry != self-reported ethnicity."""
        genotypes = genotypes_to_simple(parse_genetic_file(DEMO_FILE))
        panel = arp.load_aisnp_panel(DATA_DIR / "aisnp_panel.csv")
        associations = arp.load_associations(DATA_DIR / "ancestry_risk_associations.json")
        ancestry_result = arp.infer_ancestry(genotypes, panel)
        risks = arp.compute_disease_risks(genotypes, ancestry_result["inferred_ancestry"], associations)
        arp.generate_report(risks, ancestry_result, tmp_path)
        text = (tmp_path / "ancestry_risk_report.md").read_text()
        # Report may use "ethnicity" only in the context of distinguishing it from genetic ancestry
        assert "not" in text.lower() and ("ethnicity" in text.lower() or "super-population" in text.lower())


# ---------------------------------------------------------------------------
# TestDemoMode
# ---------------------------------------------------------------------------


# ---------------------------------------------------------------------------
# New tests for the four blocking issues flagged in the domain audit
# ---------------------------------------------------------------------------


class TestAncestryPosterior:
    """Issue 1 — ancestry over-call: infer_ancestry must emit soft posterior at low confidence."""

    def setup_method(self):
        self.panel = arp.load_aisnp_panel(DATA_DIR / "aisnp_panel.csv")

    def test_infer_ancestry_returns_posterior_key(self):
        """infer_ancestry result must include a 'posterior' probability distribution."""
        genotypes = genotypes_to_simple(parse_genetic_file(DEMO_FILE))
        result = arp.infer_ancestry(genotypes, self.panel)
        assert "posterior" in result, "Result must include 'posterior' key"

    def test_posterior_covers_all_superpopulations(self):
        genotypes = genotypes_to_simple(parse_genetic_file(DEMO_FILE))
        result = arp.infer_ancestry(genotypes, self.panel)
        for pop in ("AFR", "AMR", "EAS", "EUR", "SAS"):
            assert pop in result["posterior"], f"Missing {pop} in posterior"

    def test_posterior_sums_to_one(self):
        genotypes = genotypes_to_simple(parse_genetic_file(DEMO_FILE))
        result = arp.infer_ancestry(genotypes, self.panel)
        total = sum(result["posterior"].values())
        assert abs(total - 1.0) < 0.01, f"Posterior must sum to 1.0, got {total}"

    def test_override_posterior_is_hard_assignment(self):
        """User-supplied ancestry override must set posterior to 1.0 for that population."""
        genotypes = genotypes_to_simple(parse_genetic_file(DEMO_FILE))
        result = arp.infer_ancestry(genotypes, self.panel, ancestry_override="EAS")
        assert result["posterior"]["EAS"] == 1.0
        for pop in ("AFR", "AMR", "EUR", "SAS"):
            assert result["posterior"][pop] == 0.0

    def test_low_confidence_report_includes_posterior_table(self, tmp_path):
        """When confidence is low, the markdown report must display the posterior distribution."""
        panel_rsids = list(self.panel.keys())
        # Heterozygous AG at all panel positions creates ambiguous, low-gap likelihoods
        ambiguous_genotypes = {rsid: "AG" for rsid in panel_rsids[:arp.MIN_AISNP_COVERAGE + 5]}
        ancestry_result = arp.infer_ancestry(ambiguous_genotypes, self.panel)

        if ancestry_result["confidence"] != "low":
            pytest.skip("Input did not produce a low-confidence result.")

        associations = arp.load_associations(DATA_DIR / "ancestry_risk_associations.json")
        risks = arp.compute_disease_risks(
            ambiguous_genotypes, ancestry_result["inferred_ancestry"], associations
        )
        arp.generate_report(risks, ancestry_result, tmp_path)
        text = (tmp_path / "ancestry_risk_report.md").read_text()
        assert "posterior" in text.lower() or "probability" in text.lower(), (
            "Low-confidence report must show posterior probability distribution, not a bare hard label"
        )


class TestApol1RecessiveModel:
    """Issue 3 — APOL1 must use a compound-recessive model, not per-allele log-additive."""

    def setup_method(self):
        self.associations = arp.load_associations(DATA_DIR / "ancestry_risk_associations.json")

    def test_single_apol1_allele_is_carrier_not_full_multiplicative_or(self):
        """A single G1 heterozygote must NOT produce the old 1.89x multiplicative OR.
        Recessive model: one allele → carrier note (OR < 1.5); two alleles → high risk."""
        genotypes_carrier = {"rs73885319": "GA", "rs60910145": "CC"}
        risks = arp.compute_disease_risks(genotypes_carrier, "AFR", self.associations)
        ckd = next((r for r in risks if r.disease == "Chronic Kidney Disease"), None)
        if ckd is not None:
            assert ckd.combined_or < 1.5, (
                f"Single APOL1 allele must produce at most a carrier-level OR (<1.5). "
                f"Got {ckd.combined_or}. The per-allele multiplicative model is biologically wrong "
                f"for APOL1 — nephropathy risk is recessive (requires two high-risk alleles)."
            )

    def test_apol1_compound_het_scores_high_or(self):
        """G1+G2 compound het (one allele at each locus = two total risk alleles)
        must produce the validated compound-recessive OR (~7x), not the naive 3.3x product."""
        genotypes_compound = {"rs73885319": "GA", "rs60910145": "CT"}
        risks = arp.compute_disease_risks(genotypes_compound, "AFR", self.associations)
        ckd = next((r for r in risks if r.disease == "Chronic Kidney Disease"), None)
        assert ckd is not None, "CKD must appear for APOL1 compound het in AFR"
        assert ckd.combined_or >= 5.0, (
            f"APOL1 G1+G2 compound het must produce high CKD OR (≥5x from validated literature). "
            f"Got {ckd.combined_or}. The naive multiplicative product of individual per-allele ORs "
            f"(~3.3x) under-estimates the validated compound recessive risk (~7x)."
        )

    def test_apol1_hom_ref_produces_no_ckd_entry(self):
        """A patient carrying zero APOL1 risk alleles must not appear in CKD results."""
        genotypes_ref = {"rs73885319": "GG", "rs60910145": "CC"}
        risks = arp.compute_disease_risks(genotypes_ref, "AFR", self.associations)
        ckd = next((r for r in risks if r.disease == "Chronic Kidney Disease"), None)
        assert ckd is None, "Zero APOL1 risk alleles must produce no CKD entry."


class TestNVariants:
    """Issue 2 — DiseaseRisk must expose n_variants so the report can warn about naive ORs."""

    def setup_method(self):
        self.associations = arp.load_associations(DATA_DIR / "ancestry_risk_associations.json")

    def test_disease_risk_has_n_variants_field(self):
        genotypes = genotypes_to_simple(parse_genetic_file(DEMO_FILE))
        risks = arp.compute_disease_risks(genotypes, "SAS", self.associations)
        r = risks[0]
        assert hasattr(r, "n_variants"), "DiseaseRisk must have n_variants attribute"
        assert isinstance(r.n_variants, int)
        assert r.n_variants >= 1

    def test_n_variants_matches_variants_found_length(self):
        genotypes = genotypes_to_simple(parse_genetic_file(DEMO_FILE))
        risks = arp.compute_disease_risks(genotypes, "SAS", self.associations)
        for r in risks:
            assert r.n_variants == len(r.variants_found), (
                f"n_variants ({r.n_variants}) must equal len(variants_found) "
                f"({len(r.variants_found)}) for {r.disease}"
            )

    def test_report_disease_table_shows_variant_count(self, tmp_path):
        """The disease table must show how many variants contributed — so readers can see
        that a high combined OR is a product of N independent ORs, not a validated aggregate."""
        genotypes = genotypes_to_simple(parse_genetic_file(DEMO_FILE))
        panel = arp.load_aisnp_panel(DATA_DIR / "aisnp_panel.csv")
        ancestry_result = arp.infer_ancestry(genotypes, panel)
        risks = arp.compute_disease_risks(genotypes, ancestry_result["inferred_ancestry"], self.associations)
        arp.generate_report(risks, ancestry_result, tmp_path)
        text = (tmp_path / "ancestry_risk_report.md").read_text()
        assert "N=" in text or "n=" in text.lower() or "variant" in text.lower(), (
            "Report disease table must display variant count (N=) alongside the combined OR"
        )


class TestDemoMode:
    def test_demo_runs_without_input_file(self, tmp_path):
        arp.run_demo(tmp_path)
        assert (tmp_path / "ancestry_risk_report.md").exists()

    def test_demo_report_mentions_t2d(self, tmp_path):
        arp.run_demo(tmp_path)
        text = (tmp_path / "ancestry_risk_report.md").read_text()
        assert "Diabetes" in text

    def test_demo_report_has_or_values(self, tmp_path):
        arp.run_demo(tmp_path)
        text = (tmp_path / "ancestry_risk_report.md").read_text()
        assert "OR" in text

    def test_demo_report_has_no_absolute_risk_percentages(self, tmp_path):
        """Demo report must not show inflated absolute lifetime risk %% values."""
        arp.run_demo(tmp_path)
        text = (tmp_path / "ancestry_risk_report.md").read_text()
        # Should not have lines like "61.3%" as a lifetime risk claim
        assert "Est. Lifetime Risk" not in text


# ---------------------------------------------------------------------------
# New tests for the four blocking issues flagged in the deep domain audit
# ---------------------------------------------------------------------------


class TestDataIntegrity:
    """Audit Issue 1 — fabricated citations and direction artifact in LCT entries."""

    def setup_method(self):
        self.associations = arp.load_associations(DATA_DIR / "ancestry_risk_associations.json")

    def test_lct_entries_removed(self):
        """LCT rs4988235 entries must be removed.

        The entries assigned EUR or=0.45 (C allele is minority non-persistence allele,
        coded protective) while non-EUR ORs were 3.2–6.8x (coded as risk). Comparing
        log(OR_ancestry) − log(OR_EUR) across opposite outcome framings manufactures a
        spurious AES of 7–15x. PMID 14507249 (cited as Enattah 2002 LCT) resolves to
        Hashibe 2003 (bladder cancer survival) — a fabricated citation.
        """
        lct_entries = [
            a for a in self.associations["associations"]
            if a.get("disease") == "Lactose Intolerance" or a.get("rsid") == "rs4988235"
        ]
        assert lct_entries == [], (
            f"LCT rs4988235 Lactose Intolerance entries must be removed. "
            f"Found: {[e['rsid'] + '/' + e['ancestry'] for e in lct_entries]}. "
            "These entries mix opposite outcome framings (EUR protective vs. non-EUR risk) "
            "in the AES formula, manufacturing spurious amplification scores."
        )

    def test_no_aes_direction_artifact(self):
        """Every (or_ancestry, eur_or) pair must be on the same side of 1.0.

        An ancestry OR > 1.0 paired with eur_or < 1.0 for the same risk_allele means
        the AES formula is comparing log-ORs for opposite phenotype directions, which
        manufactures a spuriously large AES. Near-null values (within 0.1 of 1.0)
        are exempt because trivial direction ambiguity there is clinically meaningless.
        """
        for assoc in self.associations["associations"]:
            or_anc = assoc["or"]
            eur_or = assoc.get("eur_or", or_anc)
            anc_near_null = abs(or_anc - 1.0) < 0.1
            eur_near_null = abs(eur_or - 1.0) < 0.1
            if anc_near_null or eur_near_null:
                continue
            anc_is_risk = or_anc > 1.0
            eur_is_risk = eur_or > 1.0
            assert anc_is_risk == eur_is_risk, (
                f"Direction artifact in {assoc['rsid']} ({assoc['disease']}, {assoc['ancestry']}): "
                f"or_ancestry={or_anc} vs eur_or={eur_or} are on opposite sides of 1.0. "
                "The AES formula log(OR_anc) − log(OR_eur) compares different phenotype "
                "directions when one is protective and the other is risk."
            )

    def test_aldh2_entry_does_not_use_wrong_pmid(self):
        """ALDH2 rs671 must not reference PMIDs known to be wrong.

        PMID 22561518 = Jin 2012 (vitiligo GWAS), not Wu 2012 (ESCC).
        PMID 20686008 = anaesthesiology case report, not ESCC GWAS.
        """
        aldh2 = next(
            (a for a in self.associations["associations"] if a["rsid"] == "rs671"), None
        )
        assert aldh2 is not None, "ALDH2 rs671 entry must exist in the panel"
        bad_pmids = {"22561518", "20686008"}
        actual_pmid = str(aldh2.get("pmid", "")) if aldh2.get("pmid") is not None else ""
        assert actual_pmid not in bad_pmids, (
            f"ALDH2 rs671 has PMID '{actual_pmid}', which resolves to a wrong paper. "
            "22561518 = Jin 2012 vitiligo GWAS; 20686008 = anaesthesiology case report. "
            "Use the GWAS Catalog accession (GCST001563) or a verified PMID instead."
        )


class TestSoftPosteriorGating:
    """Audit Issue 3 — ancestry confidence must influence disease scoring, not just display."""

    def setup_method(self):
        self.associations = arp.load_associations(DATA_DIR / "ancestry_risk_associations.json")
        self.panel = arp.load_aisnp_panel(DATA_DIR / "aisnp_panel.csv")

    def _make_ancestry_result(self, confidence: str, posteriors: dict) -> dict:
        best = max(posteriors, key=lambda p: posteriors[p])
        return {
            "inferred_ancestry": best,
            "confidence": confidence,
            "posterior": posteriors,
            "aisnp_coverage": 35,
            "overridden": False,
            "scores": {p: 0.0 for p in posteriors},
        }

    def test_abstains_when_top_posterior_below_threshold(self):
        """When confidence is 'low' and top posterior < LOW_POSTERIOR_ABSTAIN,
        _get_risks_with_confidence_gating must return ([], note) rather than running
        disease scoring on a highly ambiguous ancestry assignment."""
        ancestry_result = self._make_ancestry_result(
            "low",
            {"AFR": 0.22, "AMR": 0.21, "EAS": 0.22, "EUR": 0.14, "SAS": 0.21},
        )
        risks, note = arp._get_risks_with_confidence_gating({}, ancestry_result, self.associations)
        assert risks == [], (
            "Must abstain from disease scoring when top posterior < LOW_POSTERIOR_ABSTAIN. "
            f"Got {len(risks)} risk entries instead of 0."
        )
        assert note is not None, "Must return a descriptive note explaining the abstention"
        assert any(kw in note.lower() for kw in ("too low", "not performed", "confidence", "ambiguous")), (
            f"Abstention note must explain why scoring was skipped. Got: {note!r}"
        )

    def test_proceeds_with_note_when_low_confidence_above_threshold(self):
        """When confidence is 'low' but top posterior >= LOW_POSTERIOR_ABSTAIN (0.35),
        _get_risks_with_confidence_gating must run scoring AND return a caveat note."""
        genotypes = genotypes_to_simple(parse_genetic_file(DEMO_FILE))
        ancestry_result = arp.infer_ancestry(genotypes, self.panel)

        if ancestry_result["confidence"] != "low":
            pytest.skip("Demo patient did not produce a low-confidence result.")

        top_posterior = max(ancestry_result["posterior"].values())
        if top_posterior < arp.LOW_POSTERIOR_ABSTAIN:
            pytest.skip(f"Demo patient top posterior {top_posterior:.2f} < abstain threshold.")

        risks, note = arp._get_risks_with_confidence_gating(genotypes, ancestry_result, self.associations)
        assert len(risks) > 0, (
            "Should still return disease risks when above the abstain threshold, even with low confidence."
        )
        assert note is not None, (
            "Should return a caveat note for low-confidence scoring (above abstain threshold)."
        )

    def test_no_note_for_high_confidence_ancestry(self):
        """When ancestry confidence is 'high', no scoring note should be emitted."""
        ancestry_result = self._make_ancestry_result(
            "high",
            {"AFR": 0.01, "AMR": 0.01, "EAS": 0.01, "EUR": 0.96, "SAS": 0.01},
        )
        _, note = arp._get_risks_with_confidence_gating({}, ancestry_result, self.associations)
        assert note is None, (
            f"No scoring note should be emitted for high-confidence ancestry assignment. Got: {note!r}"
        )

    def test_no_note_for_user_override(self):
        """When ancestry is user-supplied (overridden=True), no soft-posterior note is emitted."""
        ancestry_result = self._make_ancestry_result(
            "low",
            {"AFR": 0.22, "AMR": 0.21, "EAS": 0.22, "EUR": 0.14, "SAS": 0.21},
        )
        ancestry_result["overridden"] = True  # user explicitly supplied ancestry
        genotypes = genotypes_to_simple(parse_genetic_file(DEMO_FILE))
        _, note = arp._get_risks_with_confidence_gating(genotypes, ancestry_result, self.associations)
        assert note is None, (
            "User-supplied ancestry (--ancestry flag) bypasses the soft-posterior gate — no note needed."
        )


# ---------------------------------------------------------------------------
# TestProvenanceIntegrity — CI gate for PMID provenance correctness
#
# These tests encode the structural invariants the PR audit found violated:
# one paper reused as the source for an entire super-population across
# unrelated diseases.  They run purely against the JSON — no network calls.
# ---------------------------------------------------------------------------

_KNOWN_BAD_PMIDS = {
    # Previously-wrong PMIDs caught in successive audits.  Any re-appearance
    # of these in the panel is a regression, not a new paper being added.
    "14507249",  # Hashibe 2003 bladder cancer — cited as LCT Enattah 2002
    "20686008",  # anaesthesiology case report — cited as ALDH2 ESCC GWAS
    "22561518",  # Jin 2012 vitiligo — cited as ALDH2 ESCC GWAS (second wrong attempt)
    "23340282",  # electrochemiluminescence sensor — cited as APOL1 Genovese
    "17571276",  # Cdk5 neurodegeneration — cited as PTPN22 celiac Dubois
    "20566908",  # Tschiesner 2010 head-and-neck disability — cited as APOL1 Genovese
    "22158537",  # Cho 2011 EAS T2D — wrongly labelled as Kooner SAS T2D; used for SAS HTN/CAD/AD
    "27005778",  # Kettunen 2016 NMR metabolomics — used as AFR disease GWAS
    "23945395",  # Hara 2014 Japanese T2D (3 loci) — used for EAS CAD, BC, AF, AD
    "17478679",  # Helgadottir 2007 9p21 CAD — used for HTN rs4343/rs699 and PD rs1800497
}

# Disease categories that are biologically unrelated.  A single GWAS paper
# cannot legitimately be the primary source for associations across more than
# one of these groups.
_DISEASE_GROUPS = {
    "Type 2 Diabetes":               "metabolic",
    "Coronary Artery Disease":        "cardiovascular",
    "Hypertension":                   "cardiovascular",
    "Atrial Fibrillation":            "cardiovascular",
    "Stroke":                         "cardiovascular",
    "Chronic Kidney Disease":         "renal",
    "Breast Cancer":                  "oncology",
    "Prostate Cancer":                "oncology",
    "Esophageal Squamous Cell Cancer":"oncology",
    "Hereditary Hemochromatosis":     "metabolic",
    "Celiac Disease":                 "autoimmune",
    "Alzheimer's Disease":            "neurological",
    "Parkinson's Disease":            "neurological",
}


class TestProvenanceIntegrity:
    """CI gate: binds every active OR to a PMID that is not known-bad and does
    not exhibit the single-source back-attribution pattern (one paper used as
    the source for multiple unrelated disease categories in the same ancestry).
    """

    def setup_method(self):
        with open(DATA_DIR / "ancestry_risk_associations.json") as f:
            self.data = json.load(f)
        self.assocs = self.data["associations"]
        self.recessive = self.data.get("compound_recessive_groups", {})

    # ------------------------------------------------------------------
    # 1. No null PMIDs in active association entries
    # ------------------------------------------------------------------

    def test_no_null_pmids_in_associations(self):
        null_entries = [
            f"{a['rsid']} / {a.get('disease')} / {a.get('ancestry')}"
            for a in self.assocs
            if a.get("pmid") is None
        ]
        assert null_entries == [], (
            f"Active association entries must not have null PMIDs — use GWAS Catalog "
            f"accession or drop the entry if no paper can be confirmed.\n"
            f"Null PMID entries: {null_entries}"
        )

    def test_no_null_pmids_in_compound_recessive_groups(self):
        null_groups = [
            name for name, g in self.recessive.items()
            if g.get("pmid") is None
        ]
        assert null_groups == [], (
            f"compound_recessive_groups entries must not have null PMIDs.\n"
            f"Affected groups: {null_groups}"
        )

    # ------------------------------------------------------------------
    # 2. No known-bad PMIDs
    # ------------------------------------------------------------------

    def test_no_known_bad_pmids_in_associations(self):
        violations = [
            f"{a['rsid']} / {a.get('disease')} / {a.get('ancestry')} → pmid={a['pmid']}"
            for a in self.assocs
            if str(a.get("pmid", "")) in _KNOWN_BAD_PMIDS
        ]
        assert violations == [], (
            "Known-bad PMIDs detected in association panel — these resolve to wrong papers "
            "(wrong disease, wrong ancestry, or unrelated study).\n"
            f"Violations:\n" + "\n".join(f"  {v}" for v in violations)
        )

    def test_no_known_bad_pmids_in_compound_recessive_groups(self):
        violations = [
            f"{name} → pmid={g['pmid']}"
            for name, g in self.recessive.items()
            if str(g.get("pmid", "")) in _KNOWN_BAD_PMIDS
        ]
        assert violations == [], (
            f"Known-bad PMIDs in compound_recessive_groups: {violations}"
        )

    # ------------------------------------------------------------------
    # 3. No single PMID sourcing associations across >1 disease group
    #
    # A T2D GWAS may cover multiple T2D loci across ancestries (same disease
    # group: "metabolic").  But the same paper cannot legitimately be the
    # primary source for associations in both "metabolic" and "cardiovascular"
    # categories — that is the signature of the blanket back-attribution bug.
    # ------------------------------------------------------------------

    def test_no_pmid_spans_multiple_disease_groups(self):
        from collections import defaultdict
        pmid_to_groups: dict = defaultdict(set)
        pmid_to_examples: dict = defaultdict(list)

        for a in self.assocs:
            pmid = str(a.get("pmid", ""))
            if not pmid or pmid == "None":
                continue
            disease = a.get("disease", "")
            group = _DISEASE_GROUPS.get(disease, disease)
            pmid_to_groups[pmid].add(group)
            pmid_to_examples[pmid].append(
                f"{a['rsid']} {disease} ({a.get('ancestry')})"
            )

        violations = []
        for pmid, groups in pmid_to_groups.items():
            if len(groups) > 1:
                violations.append(
                    f"PMID {pmid} spans disease groups {groups}:\n"
                    + "\n".join(f"    {ex}" for ex in pmid_to_examples[pmid])
                )

        assert violations == [], (
            "Single PMID used as source across multiple unrelated disease categories — "
            "this is the back-attribution pattern that produces fabricated provenance.\n"
            "A T2D GWAS cannot be the source of a CAD or AD odds ratio.\n\n"
            + "\n".join(violations)
        )

    # ------------------------------------------------------------------
    # 3b. No inert baseline_prevalences block (double-counting hazard)
    # ------------------------------------------------------------------

    def test_no_baseline_prevalences_block(self):
        assert "baseline_prevalences" not in self.data, (
            "The inert `baseline_prevalences` block must not be present in "
            "ancestry_risk_associations.json. Absolute-risk scoring was removed in "
            "v1.3.0 to avoid double-counting; leaving the prevalence table in the file "
            "leaves the double-counting bug one wiring change away from returning."
        )

    # ------------------------------------------------------------------
    # 4. All ORs are positive and plausible (catches transcription errors
    #    that would silently produce nonsense AES values)
    # ------------------------------------------------------------------

    def test_all_ors_are_positive(self):
        bad = [
            f"{a['rsid']} / {a.get('disease')} / {a.get('ancestry')} or={a['or']}"
            for a in self.assocs
            if not (0.01 <= a.get("or", 0) <= 100)
        ]
        assert bad == [], (
            f"OR values must be in the range [0.01, 100]. Out-of-range entries:\n"
            + "\n".join(f"  {b}" for b in bad)
        )

    # ------------------------------------------------------------------
    # 5. HFE and APOL1 must not be on the additive path
    # ------------------------------------------------------------------

    def test_hfe_is_recessive_model(self):
        hfe = next((a for a in self.assocs if a["rsid"] == "rs1800562"), None)
        assert hfe is not None, "HFE rs1800562 entry must exist"
        assert hfe.get("model") == "recessive_compound", (
            f"HFE rs1800562 must use model='recessive_compound'. "
            f"Got model={hfe.get('model')!r}. "
            "Additive path gives heterozygotes a spurious 9.8x and homozygotes ~96x."
        )

    def test_apol1_entries_are_recessive_model(self):
        apol1_rsids = {"rs73885319", "rs60910145"}
        for a in self.assocs:
            if a["rsid"] in apol1_rsids:
                assert a.get("model") == "recessive_compound", (
                    f"APOL1 {a['rsid']} must use model='recessive_compound'. "
                    f"Got model={a.get('model')!r}."
                )

    # ------------------------------------------------------------------
    # 6. AISNP panel contains no known near-zero-FST candidate-gene SNPs
    # ------------------------------------------------------------------

    def test_aisnp_panel_excludes_low_fst_markers(self):
        low_fst_rsids = {
            "rs731236", "rs2228570",   # VDR
            "rs1801133", "rs1801131",  # MTHFR
            "rs1800497",               # ANKK1/DRD2
            "rs4680",                  # COMT
            "rs53576",                 # OXTR
        }
        with open(DATA_DIR / "aisnp_panel.csv") as f:
            import csv as _csv
            panel_rsids = {row["rsid"] for row in _csv.DictReader(f)}

        found = low_fst_rsids & panel_rsids
        assert found == set(), (
            f"AISNP panel contains near-zero-FST markers that provide no population-discriminatory "
            f"signal and inflate the coverage count toward the 30-marker abstention gate:\n"
            f"  {found}\n"
            "These are pharmacogenomic candidate-gene SNPs (VDR, MTHFR, COMT, OXTR, ANKK1), "
            "not ancestry-informative markers."
        )
